In [1]:
print("austin")

austin


In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr))



[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr[0,1,2])

6


In [19]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,0:1])

[1]


In [21]:
import pandas as pd

In [27]:
a=[1,2,3]
a1=pd.Series(a,index=["x","y","z"])
a1


x    1
y    2
z    3
dtype: int64

In [39]:
abc={"a":[10,100,1000],"b":[20,200,2000]}
a2=pd.DataFrame(abc,index=["x","y","z"])
a2

a     b
x    10    20
y   100   200
z  1000  2000

In [45]:
abc={"a":[10,100,1000],"b":[20,200,2000]}
a2=pd.DataFrame(abc)
a2 = a2.set_index("a")
a2

b
a         
10      20
100    200
1000  2000

In [47]:
import pandas as pd
data = {
    "a": [1,2,3],
    "b" : [20,200,2000],
}
df = pd.DataFrame(data)
df = df.set_index("a")
df


b
a      
1    20
2   200
3  2000